<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPRUSARW1003" name="Support page testing" tests="7" failures="2" timestamp="31 May 2018 09:25:14 GMT" time="139.44" errors="0">
  <testcase name="" time="4.016" classname="tests.supportPageTests.SupportTest"/>
  <testcase name="" time="6.866" classname="tests.supportPageTests.SupportTest"/>
  <testcase name="" time="35.956" classname="tests.supportPageTests.SupportTest"/>
  <testcase name="" time="5.94" classname="tests.supportPageTests.SupportTest">
    <failure type="java.lang.AssertionError" message="The question with invalid data is exist expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The question with invalid data is exist expected [false] but found [true]
	at tests.supportPageTests.SupportTest.askQuestionWithInvalidText(SupportTest.java:44)
	at runner.Runner.run(Runner.java:49)
	at runner.Runner.main(Runner.java:22)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!--  -->
  <testcase name="" time="6.963" classname="tests.supportPageTests.SupportTest">
    <failure type="java.lang.AssertionError" message="The question with invalid data is exist expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The question with invalid data is exist expected [false] but found [true]
	at tests.supportPageTests.SupportTest.askQuestionWithInvalidText(SupportTest.java:44)
	at runner.Runner.run(Runner.java:49)
	at runner.Runner.main(Runner.java:22)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!--  -->
  <testcase name="" time="35.926" classname="tests.supportPageTests.SupportTest"/>
  <testcase name="" time="35.971" classname="tests.supportPageTests.SupportTest"/>
</testsuite> <!-- Support page testing -->
